name: Deploy to AWS EC2

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          client/package-lock.json
          server/package-lock.json
          
    - name: Install server dependencies
      run: |
        cd server
        npm ci
        
    - name: Install client dependencies
      run: |
        cd client
        npm ci
        
    - name: Build frontend
      run: |
        cd client
        npm run build
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          cd /var/www/cashgit.com
          
          # 备份当前版本
          if [ -d "backup" ]; then
            rm -rf backup
          fi
          mkdir -p backup
          cp -r client/build backup/client_build_$(date +%Y%m%d_%H%M%S)
          cp -r server backup/server_$(date +%Y%m%d_%H%M%S)
          
          # 停止后端服务
          pm2 stop cashgit-backend || true
          
          # 等待服务完全停止
          sleep 5
          
          echo "Backup completed and backend stopped"
          
    - name: Upload built files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT }}
        source: "client/build/*"
        target: "/var/www/cashgit.com/client/build"
        strip_components: 2
        
    - name: Upload server files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT }}
        source: "server/*"
        target: "/var/www/cashgit.com/server"
        strip_components: 1
        
    - name: Upload Nginx config
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT }}
        source: "nginx-cashgit.conf"
        target: "/tmp/nginx-cashgit.conf"
        
    - name: Restart services
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          cd /var/www/cashgit.com/server
          
          # 安装新的依赖
          npm ci --only=production
          
          # 更新Nginx配置
          sudo cp /tmp/nginx-cashgit.conf /etc/nginx/sites-available/cashgit.com
          sudo nginx -t && sudo systemctl reload nginx
          
          # 启动后端服务
          pm2 start cashgit-backend
          
          # 检查服务状态
          pm2 status
          
          echo "Deployment completed successfully!"
